# Generated by Django 4.2.9 on 2026-02-04 14:56

import core.models
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_child_alternate_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='child',
            name='core_child_last_na_66f284_idx',
        ),
        migrations.RemoveIndex(
            model_name='child',
            name='core_child_overall_idx',
        ),
        migrations.RemoveIndex(
            model_name='child',
            name='core_child_caseload_idx',
        ),
        migrations.RemoveIndex(
            model_name='child',
            name='core_child_on_hold_idx',
        ),
        migrations.RemoveField(
            model_name='child',
            name='guardian1_phone',
        ),
        migrations.RemoveField(
            model_name='child',
            name='guardian2_phone',
        ),
        migrations.AddField(
            model_name='child',
            name='agency_continuing_involvement',
            field=models.BooleanField(default=False, help_text='Referring agency continuing involvement'),
        ),
        migrations.AddField(
            model_name='child',
            name='attends_childcare',
            field=models.BooleanField(default=False, help_text='Attending licensed childcare'),
        ),
        migrations.AddField(
            model_name='child',
            name='attends_earlyon',
            field=models.BooleanField(default=False, help_text='Attending EarlyON Child and Family Center'),
        ),
        migrations.AddField(
            model_name='child',
            name='childcare_centre',
            field=models.ForeignKey(blank=True, help_text='Childcare centre (if attending)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childcare_children', to='core.centre'),
        ),
        migrations.AddField(
            model_name='child',
            name='childcare_frequency',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='How often attending childcare'),
        ),
        migrations.AddField(
            model_name='child',
            name='earlyon_centre',
            field=models.ForeignKey(blank=True, help_text='EarlyON centre (if attending)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earlyon_children', to='core.centre'),
        ),
        migrations.AddField(
            model_name='child',
            name='earlyon_frequency',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='How often attending EarlyON'),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian1_cell_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian1_home_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian1_work_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian2_cell_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Second Guardian Cell Phone'),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian2_home_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Second Guardian Home Phone'),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian2_work_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Second Guardian Work Phone'),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_agency_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Agency address (if other_agency)'),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_agency_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Agency name (if other_agency)'),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_consent_on_file',
            field=models.BooleanField(default=False, help_text='Referral consent form on file'),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_cognitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_details',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Details about referral reasons'),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_fine_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_gross_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_self_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason_social_emotional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_source_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Name of person/contact referring'),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_source_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_source_type',
            field=models.CharField(blank=True, choices=[('parent_guardian', 'Parent/Guardian'), ('other_agency', 'Other Agency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Current centre for caseload (can be empty for non-caseload children)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.centre'),
        ),
        migrations.AlterField(
            model_name='child',
            name='start_date',
            field=models.DateField(default=core.models.get_today),
        ),
        migrations.AlterField(
            model_name='visit',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Child who received the visit (null for site visits)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='core.child'),
        ),
    ]
